/*
 RMIT University Vietnam
 Course: COSC2659 iOS Development
 Semester: 2022B
 Assessment: Assignment 1
 Author: Nguyen Thi Huong Thao
 ID: s3891825
 Created  date: 28/07/2022
 Last modified: 07/08/2022
 Acknowledgement: Acknowledge the resources that you use here.
 */
//
//  AlbumData.swift
//  ThaoNguyen-Assignment1
//
//  Created by Nguyễn Thảo on 29/07/2022.
//

import Foundation
import MapKit

var albums:[Album] =
[
    Album(albumName: "The Red Summer", artist: "Red Velvet", logo: "red-velvet-logo", imageName: ["red-velvet","flavor-1", "flavor-2", "muacd"], description: "The Red Summer is the first special extended play and the fifth overall by South Korean girl group Red Velvet. Marketed as the group's first `special summer` release, the five-track EP was released digitally on July 9, 2017, and physically the following day by SM Entertainment. Primarily a dance-pop and EDM record, it is the second major release from Red Velvet to focus solely on their `red` concept, following their debut studio album The Red (2015). It was later proceeded by Summer Magic as both the second `special summer` extended play and the third major `red` release.", genre: "Pop, EDM, tropical house", tracklist: ["1. Red Flavor", "2. You Better Know", "3. Zoo", "4. Mojito", "5. Hear The Sea"], link: "https://en.wikipedia.org/wiki/The_Red_Summer_(EP)", coordinates:  CLLocationCoordinate2D(latitude: 10.78579121575812, longitude: 106.67867364602188), locationName: "MuaCDShop - Kpop Store", address: "85 Trần Quang Diệu, Phường 13, Quận 3, Thành phố Hồ Chí Minh, Vietnam"),
    Album(albumName: "Purpose", artist: "Taeyeon", logo: "taeyeon-logo",  imageName: ["purpose", "purpose-1", "purpose-2","izi2buy"], description: "Purpose is the second studio album by South Korean singer Taeyeon. It was released through SM Entertainment on October 28, 2019. It features 12 tracks, including the Gaon number-one single `Four Seasons` and its B-side `Blue` alongside ten new tracks, including the title track `Spark`. On January 15, 2020, a repackage edition of Purpose was released including three new songs, including title track `Dear Me`.", genre: "Ballad, R&B, Blues, Jazz", tracklist: ["1. Here I Am", "2. Spark", "3. Find Me", "4. Love You Like Crazy", "5. Better Babe", "6. Wine", "7. Do You Love Me?"], link: "https://en.wikipedia.org/wiki/Purpose_(Taeyeon_album)", coordinates: CLLocationCoordinate2D(latitude: 10.784203938897816,  longitude: 106.68553316308905), locationName: "KPOP Shop - izi2buy.com", address: "115-1 Trần Quốc Thảo, Võ Thị Sáu, Quận 3, Thành phố Hồ Chí Minh 722713, Vietnam"),
    Album(albumName: "Position", artist: "Ariana Grande", logo: "ariana-grande-logo", imageName: ["position-1", "sweetener", "position-2", "bn"], description: "Positions is the sixth studio album by American singer Ariana Grande. It was released by Republic Records on October 30, 2020. Grande created the album with focus on her vocals, while its subject matter conveyed emotional healing.[1] Grande worked with numerous producers on Positions, including frequent collaborator Tommy Brown, accompanied by longtime co-writers Victoria Monét and Tayla Parx.", genre: "Pop, R&B", tracklist: ["1. shut up", "2. 34+35", "3. motive feat. doja cat", "4. just like magic", "5. six thirty", "6. off the table feat. the weeknd", "7. my hair"], link: "https://en.wikipedia.org/wiki/Positions_(album)", coordinates: CLLocationCoordinate2D(latitude: 39.06424879920283, longitude: -77.12657599259302), locationName: "Barnes & Noble", address: "Congressional Plaza, 1603 Rockville Pike, Rockville, MD 20852, United States"),
    Album(albumName: "Blue Neighborhood", artist: "Troye Sivan", logo: "troye-logo", imageName: ["blue-1", "blue-2", "blue-3", "beats"], description: "Blue Neighbourhood is the debut studio album by Australian singer and songwriter Troye Sivan. It was released internationally on 4 December 2015 via EMI Music Australia and Capitol Records America.[1] The album is preceded by Sivan's fourth extended play Wild, which served as a 6-song opening installment to Blue Neighbourhood.", genre: "ElectroPop, Gloom-Pop, Synth-Pop", tracklist: ["1. WILD", "2. FOOLS", "3. EASE", "4. TALK ME DOWN", "5. COOL", "6. HEAVEN", "7. YOUTH", "8. LOST BOY"], link: "https://en.wikipedia.org/wiki/Blue_Neighbourhood)", coordinates: CLLocationCoordinate2D(latitude: 39.97924042546293, longitude: -75.1784625), locationName: "Brewerytown Beats", address: "1517 N Bailey St, Philadelphia, PA 19121, USA"),
    Album(albumName: "Savage", artist: "aespa", logo: "aespa-logo", imageName: ["savage", "savage-1", "savage-2", "beats"], description: "`Savage` is a song recorded by South Korean girl group Aespa for their first extended play (EP) of the same name. It was released as the lead single on October 5, 2021, by SM Entertainment. Described as a `hyperpop-tinged title track`, the song was written by Yoo Young-jin, who also composed along with Kirsten Collins, Jia Lih, and Hautboi Rich, and eventually handled the arrangement alongside Lih. It also continues the group's previous storyline in `Next Level`, with the members and their corresponding avatars confronting their Black Mamba villain in the fictional Kwangya universe.", genre: "EDM trap, Dubstep, Hyperpop", tracklist: ["1. aenergy", "2. Savage", "3. I'll make you cry", "4. YEPPI YEPPI", "5. ICONIC", "6. Lucid Dream"], link: "https://en.wikipedia.org/wiki/Savage_(Aespa_song)", coordinates: CLLocationCoordinate2D(latitude: 39.97924042546293, longitude: -75.1784625), locationName: "Brewerytown Beats", address: "1517 N Bailey St, Philadelphia, PA 19121, USA"),
    Album(albumName: "Sticker", artist: "NCT127", logo: "NCT27-logo" ,imageName: ["sticker-1", "sticker", "sticker-2", "muacd"], description: "Sticker is the third Korean-language and fourth overall studio album by South Korean boy band NCT 127. It was released on September 17, 2021, by SM Entertainment through Dreamus in South Korea and Virgin Music in United States. It follows their Japanese-language EP Loveholic, released in February 2021, and previous Korean-language studio album Neo Zone, released in March 2020.[6] On October 25, the group released a repackaged version of Sticker, titled Favorite, which features three new tracks, including the lead single `Favorite (Vampire)`.[7]", genre: "HipHop, R&B, Pop, Dance", tracklist: ["1. Sticker", "2. Lemonade", "3. Breakfast", "4. Focus", "5. The Rainy Night", "6. Bring The Noize", "7. Magic Carpet Ride"], link: "https://en.wikipedia.org/wiki/Sticker_(album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922), locationName: "MuaCDShop - Kpop Store", address: "85 Trần Quang Diệu, Phường 13, Quận 3, Thành phố Hồ Chí Minh, Vietnam"),
    Album(albumName: "Planet Her", artist: "Doja Cat", logo: "doja-cat-logo",  imageName: ["planet", "planet-1", "planet-2", "beats"], description: "Planet Her is the third studio album by American rapper and singer Doja Cat. It was released on June 25, 2021, by Kemosabe and RCA Records. The album, titled after a fictional planet created by Doja Cat, sees her experimenting with sounds that were new and unfamiliar to her before, in an attempt to depart from mainstream music trends. She likened the shift in her musical style to travelling outside the Earth and into outer space.", genre: "Pop, Hip Hop, R&B", tracklist: ["1. Woman", "2. Naked", "3. Get Into It (Yuh)", "4. Need to Know", "5. I Don't Do Drugs", "6. Love to Dream", "7. You Right", "8. Been Like This"], link: "https://en.wikipedia.org/wiki/Planet_Her", coordinates: CLLocationCoordinate2D(latitude: 39.97924042546293, longitude: -75.1784625), locationName: "Brewerytown Beats", address: "1517 N Bailey St, Philadelphia, PA 19121, USA"),
    Album(albumName: "1989", artist: "Taylor Swift", logo: "taylor-swift-logo",  imageName: ["1989","1989-1","1989-2", "mainstreet"], description: "1989 is the fifth studio album by American singer-songwriter Taylor Swift. It was released on October 27, 2014, by Big Machine Records. Following the release of her genre-spanning fourth studio album Red (2012), noted for its pop hooks and electronic accents, the media questioned the validity of Swift's status as a country artist. Inspired by 1980s synth-pop to create a record that shifted her sound and image from country to mainstream pop, Swift enlisted Max Martin as co-executive producer, and titled her fifth album after her birth year as a symbolic rebirth of her artistry.",  genre: "Synth-Pop", tracklist: ["1. Welcome To New York ", "2. Blank Space", "3. Style", "4. Out of the Woods", "5. All You Had to Do Was Stay", "6. Shake It Off", "7. Bad Blood", "8. Wildest Dreams"], link: "https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)", coordinates: CLLocationCoordinate2D(latitude: 40.02655847088985, longitude: -75.22624129340565), locationName: "Main Street Music", address: "4444 Main St, Philadelphia, PA 19127, USA"),
    Album(albumName: "Nine Track Mind", artist: "Charlie Puth", logo: "charlie-puth-logo", imageName: ["charlie-puth","puth-1","puth-2","mainstreet"], description: "Nine Track Mind is the debut studio album by American singer Charlie Puth. It was released on January 29, 2016, by Artist Partner Group and Atlantic Records, after being scheduled to be released on November 6, 2015.", genre: "Pop, R&B", tracklist: ["1. One Call Away", "2. Dangerously", "3. Marvin Gaye", "4. Losing My Mind", "5. We Don't Talk Anymore", "6. My Gospel", "7. Up All Night", "8. Left Right Left"], link: "https://en.wikipedia.org/wiki/Nine_Track_Mind", coordinates: CLLocationCoordinate2D(latitude: 40.02655847088985, longitude: -75.22624129340565), locationName: "Main Street Music", address: "4444 Main St, Philadelphia, PA 19127, USA")
    
]
