//
//  AlbumData.swift
//  ThaoNguyen-Assignment1
//
//  Created by Nguyễn Thảo on 29/07/2022.
//

import Foundation
import MapKit

var albums:[Album] =
[
    Album(albumName: "The Red Summer", artist: "Red Velvet", logo: "red-velvet-logo", imageName: ["red-velvet","flavor-1", "flavor-2"], description: "The Red Summer is the first special extended play and the fifth overall by South Korean girl group Red Velvet. Marketed as the group's first `special summer` release, the five-track EP was released digitally on July 9, 2017, and physically the following day by SM Entertainment. Primarily a dance-pop and EDM record, it is the second major release from Red Velvet to focus solely on their `red` concept, following their debut studio album The Red (2015). It was later proceeded by Summer Magic as both the second `special summer` extended play and the third major `red` release.", genre: "Pop, EDM, tropical house", link: "https://en.wikipedia.org/wiki/The_Red_Summer_(EP)", coordinates:  CLLocationCoordinate2D(latitude: 10.78579121575812, longitude: 106.67867364602188)),
    Album(albumName: "Position", artist: "Ariana Grande", logo: "ariana-grande-logo", imageName: ["sweetener", "position-1", "position-2"], description: "Positions is the sixth studio album by American singer Ariana Grande. It was released by Republic Records on October 30, 2020. Grande created the album with focus on her vocals, while its subject matter conveyed emotional healing.[1] Grande worked with numerous producers on Positions, including frequent collaborator Tommy Brown, accompanied by longtime co-writers Victoria Monét and Tayla Parx.", genre: "Pop, R&B", link: "https://en.wikipedia.org/wiki/Positions_(album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "Purpose", artist: "Justin Bieber", logo: "jb-logo", imageName: ["purpose-jb"], description: "Purpose is the fourth studio album by Canadian singer Justin Bieber. It was released through Def Jam Recordings and School Boy Records on November 13, 2015, as the follow-up to his 2012 album “Believe”. The album features guest appearances from Big Sean, Travis Scott, Halsey, Skrillex, Diplo, and Ariana Grande. The deluxe version was released simultaneously on the same day. It features an extra guest appearance from Nas. Production was handled by Bieber himself, Skrillex and Diplo from Jack Ü, BloodPop, Benny Blanco, the Audibles, Soundz, Mike Dean, Ian Kirkpatrick, and Andre Harris, among others.", genre: "Pop, R&B, Soul, EDM, Dance-Pop", link: "https://en.wikipedia.org/wiki/Purpose_(Justin_Bieber_album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "Sticker", artist: "NCT127", logo: "NCT27-logo" ,imageName: ["sticker"], description: "Sticker is the third Korean-language and fourth overall studio album by South Korean boy band NCT 127. It was released on September 17, 2021, by SM Entertainment through Dreamus in South Korea and Virgin Music in United States. It follows their Japanese-language EP Loveholic, released in February 2021, and previous Korean-language studio album Neo Zone, released in March 2020.[6] On October 25, the group released a repackaged version of Sticker, titled Favorite, which features three new tracks, including the lead single `Favorite (Vampire)`.[7]", genre: "HipHop, R&B, Pop, Dance", link: "https://en.wikipedia.org/wiki/Sticker_(album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "Planet Her", artist: "Doja Cat", logo: "doja-cat-logo",  imageName: ["planet"], description: "Planet Her is the third studio album by American rapper and singer Doja Cat. It was released on June 25, 2021, by Kemosabe and RCA Records. The album, titled after a fictional planet created by Doja Cat, sees her experimenting with sounds that were new and unfamiliar to her before, in an attempt to depart from mainstream music trends. She likened the shift in her musical style to travelling outside the Earth and into outer space.", genre: "Pop, Hip Hop, R&B", link: "https://en.wikipedia.org/wiki/Planet_Her", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "1989", artist: "Taylor Swift", logo: "taylor-swift-logo",  imageName: ["1989","1989-1","1989-2"], description: "1989 is the fifth studio album by American singer-songwriter Taylor Swift. It was released on October 27, 2014, by Big Machine Records. Following the release of her genre-spanning fourth studio album Red (2012), noted for its pop hooks and electronic accents, the media questioned the validity of Swift's status as a country artist. Inspired by 1980s synth-pop to create a record that shifted her sound and image from country to mainstream pop, Swift enlisted Max Martin as co-executive producer, and titled her fifth album after her birth year as a symbolic rebirth of her artistry.",  genre: "Synth-Pop", link: "https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "Nine Track Mind", artist: "Charlie Puth", logo: "charlie-puth-logo", imageName: ["charlie-puth"], description: "Nine Track Mind is the debut studio album by American singer Charlie Puth. It was released on January 29, 2016, by Artist Partner Group and Atlantic Records, after being scheduled to be released on November 6, 2015.", genre: "Pop, R&B", link: "https://en.wikipedia.org/wiki/Nine_Track_Mind", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922)),
    Album(albumName: "Purpose", artist: "Taeyeon", logo: "taeyeon-logo",  imageName: ["purpose"], description: "Purpose is the second studio album by South Korean singer Taeyeon. It was released through SM Entertainment on October 28, 2019. It features 12 tracks, including the Gaon number-one single `Four Seasons` and its B-side `Blue` alongside ten new tracks, including the title track `Spark`. On January 15, 2020, a repackage edition of Purpose was released including three new songs, including title track `Dear Me`.", genre: "Ballad, R&B, Blues, Jazz", link: "https://en.wikipedia.org/wiki/Purpose_(Taeyeon_album)", coordinates: CLLocationCoordinate2D(latitude: 41.8902, longitude: 12.4922))
]
